baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Minimal"

[params]
  Subtitle = "minimal site"
  GithubID = "Your Github ID"
  TwitterID = "hiroriin"
  AnalyticsID = "Your Google Analytics tracking code"
  DisqusShortname = "Your Disqus shortname"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
